export const metadata = {
  title: 'Asteroid info',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <section>{children}</section>
  );
}
